import { SlashCommandBuilder, AttachmentBuilder } from 'discord.js';
import db from '../../database/db.js';
import { isStaff } from '../../utils/permissions.js';
import { successEmbed, errorEmbed } from '../../utils/embeds.js';
import { generateTranscript } from '../../utils/transcript.js';
import { sendTicketLog } from '../../utils/logger.js';
import config from '../../config/loadConfig.js';

export default {
  data: new SlashCommandBuilder()
    .setName('transcript')
    .setDescription('Generate an HTML transcript of the current ticket'),

  async execute(interaction) {
    const ticket = db.prepare('SELECT * FROM tickets WHERE channel_id = ?').get(interaction.channel.id);

    if (!ticket) {
      return interaction.reply({ embeds: [errorEmbed('Error', 'This is not a ticket channel.')], ephemeral: true });
    }

    const isOwner = ticket.user_id === interaction.user.id;
    if (!isOwner && !isStaff(interaction.member, config)) {
      return interaction.reply({ embeds: [errorEmbed('Permission Denied', 'You cannot generate a transcript for this ticket.')], ephemeral: true });
    }

    await interaction.deferReply({ ephemeral: true });

    const transcript = await generateTranscript(interaction.channel, {
      type: ticket.type,
      userId: ticket.user_id
    });

    const attachment = new AttachmentBuilder(transcript.filepath, { name: transcript.filename });

    await sendTicketLog(interaction.guild, interaction.client, '📄 Transcript Generated', [
      { name: 'Ticket', value: `${interaction.channel}`, inline: true },
      { name: 'Generated By', value: `${interaction.user}`, inline: true },
      { name: 'Messages', value: `${transcript.messageCount}`, inline: true }
    ]);

    await interaction.editReply({
      embeds: [successEmbed('Transcript Generated', `Transcript contains **${transcript.messageCount}** message(s).`)],
      files: [attachment]
    });
  }
};
